### ISSUE TITLE
Import data_helper and process get killed by itself

### ISSUE THREAD

**Issue by Simon006** [ssbuild/deep_training#2]
![image](https://user-images.githubusercontent.com/44133055/225807498-bb5a1936-1bc1-493c-9b7a-1ef5889060cc.png)
![image](https://user-images.githubusercontent.com/44133055/225807593-39cf8f2b-30e9-4e11-ba10-b515cb453c66.png)
我在windows上运行chatglm-finetune没有问题，但是num_layers设置成一都会GPU爆内存，在linux上运行的时候这个deep_training的包引入有些问题，会自动把自己kill掉。
有什么解决办法吗？

**Comment by Simon006** [comment]
好像解决了，我的别的训练程序存在内存泄漏 RAM满了，
cat /proc/meminfo发现内存满了
pkill python之后可以正常使用了

**Comment by ssbuild** [comment]
> 好像解决了，我的别的训练程序存在内存泄漏 RAM满了， cat /proc/meminfo发现内存满了 pkill python之后可以正常使用了

killed 一般都是系统内存不足
