### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by maojinyang** [ssbuild/deep_training#3]
请问为什么在已经安装deep_training库的情况下仍然会有以下的报错？

ModuleNotFoundError: No module named 'deep_training'

![image](https://user-images.githubusercontent.com/95010088/226160869-d293fd24-bb5d-49f4-8583-b6c8c75002c3.png)

**Comment by ssbuild** [comment]
> deep_training

 从经验看是conda环境本机环境串了，检查下本机conda 环境 确认安装位置，所使用的python版本和安装位置

**Comment by maojinyang** [comment]
感谢回复！

**Comment by maojinyang** [comment]
我发现直接pip安装没有问题，而下载源码安装就会报ModuleNotFoundError的错误，反馈一下。

**Comment by ssbuild** [comment]
> 我发现直接pip安装没有问题，而下载源码安装就会报ModuleNotFoundError的错误，反馈一下。

路径问题。 最简单的方法就是随便安装一个deep_training, 然后找到安装目录，用新源码覆盖这样最简单。
